src/Entity/Sites.php
<?php

namespace App\Entity;

use App\Repository\SitesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SitesRepository::class)
 */
class Sites
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $nom_site;

    /**
     * @ORM\OneToMany(targetEntity=Participant::class, mappedBy="sites")
     */
    private $participants;

    /**
     * @ORM\OneToMany(targetEntity=Sorties::class, mappedBy="site")
     */
    private $sorties;

    public function __construct()
    {
        $this->participants = new ArrayCollection();
        $this->sorties = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomSite(): ?string
    {
        return $this->nom_site;
    }

    public function setNomSite(string $nom_site): self
    {
        $this->nom_site = $nom_site;

        return $this;
    }

    /**
     * @return Collection|Participant[]
     */
    public function getParticipants(): Collection
    {
        return $this->participants;
    }

    public function addParticipant(Participant $participant): self
    {
        if (!$this->participants->contains($participant)) {
            $this->participants[] = $participant;
            $participant->setSites($this);
        }

        return $this;
    }

    public function removeParticipant(Participant $participant): self
    {
        if ($this->participants->removeElement($participant)) {
            // set the owning side to null (unless already changed)
            if ($participant->getSites() === $this) {
                $participant->setSites(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->getNomSite();
    }

    /**
     * @return Collection|Sorties[]
     */
    public function getSorties(): Collection
    {
        return $this->sorties;
    }

    public function addSorty(Sorties $sorty): self
    {
        if (!$this->sorties->contains($sorty)) {
            $this->sorties[] = $sorty;
            $sorty->setSite($this);
        }

        return $this;
    }

    public function removeSorty(Sorties $sorty): self
    {
        if ($this->sorties->removeElement($sorty)) {
            // set the owning side to null (unless already changed)
            if ($sorty->getSite() === $this) {
                $sorty->setSite(null);
            }
        }

        return $this;
    }
}

src/Form/SitesType.php
<?php

namespace App\Form;

use App\Entity\Sites;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SitesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom_site')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Sites::class,
        ]);
    }
}

src/Controller/SitesController.php
<?php

namespace App\Controller;

use App\Entity\Sites;
use App\Entity\Sorties;
use App\Form\SitesType;
use App\Repository\LieuxRepository;
use App\Repository\ParticipantRepository;
use App\Repository\SitesRepository;
use App\Repository\SortiesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class SitesController extends AbstractController
{
    /**
     * @Route("/sites", name="sites")
     */
    public function sitesSelect(SitesRepository $sites,Request $req): Response
    {
        $lstSites = $sites->findAll();

        return $this->render('sites/site.html.twig', [
            'lstSites' => $lstSites,
        ]);
    }

    /**
     * @Route("/admin/sites/add", name="site_add")
     */
    public function sitesAdd(EntityManagerInterface $em, Request $req): Response
    {
        $site = new Sites();
        $site->setNomSite($req->get('search_sites'));

        $em->persist($site);
        $em->flush();

        return $this->redirectToRoute("sites");
    }

    /**
     * @Route("/admin/sites/update/{id}", name="site_update")
     */
    public function sitesUpdate(Sites $site, EntityManagerInterface $em, Request $req): Response
    {
        $form = $this->createForm(SitesType::class,$site);
        $form->handleRequest($req);

        if($form->isSubmitted() && $form->isValid()){
            $em->flush();
            return $this->redirectToRoute("sites");
        }

        return $this->render('sites/sitesmodif.html.twig',[
            'forms' => $form->createView()
        ]);
    
    }

    /**
     * @Route("/admin/sites/del/{id}", name="site_delete")
     */
    public function sitesDelete(Sites $site, EntityManagerInterface $em): Response
    {
        foreach($site->getSorties() as $s){
            $s->setSite(null);
        }

        foreach($site->getParticipants() as $p){
            $p->setSites(null);
        }
        $em->remove($site);
        $em->flush();

        return $this->redirectToRoute('sites');
    }

    /**
     * @Route("/sites/search", name="sites_search")
     */
    public function sitesSearch(SitesRepository $sites,Request $req): Response
    {

        if($req->get('filter_sites') == null){
            return $this->redirectToRoute("sites");    
        }else{
            $lstSites = $sites->filterSearchSitesByName($req->get('filter_sites'));

            return $this->render('sites/site.html.twig', [
                'lstSites' => $lstSites,
            ]);
        }
    }

    /**
     * @Route("/site/{id}/sorties", name="sorties_site")
     */
    public function sorties_site(Sites $s, SortiesRepository $sr, ParticipantRepository $pr): Response
    {
        $organisateurs = $pr->findBy(array("sites" => $s->getId()));
        $sorties = $sr->findBy(array("organisateur" => $organisateurs));
        
        return $this->render('sites/sorties.html.twig', [
            "site" => $s,
            "sorties" => $sorties
        ]);
    }
}

templates/sites/site.html.twig
{% extends 'base.html.twig' %}

{% block body %}

	<div class="h" id="gestion-sites">
		<h1 class="title-page">Gérer les sites</h1>

		<div class="filter">
			<h2 class="mb-3">Filter les sites</h2>

			<form class="row g-3" action="{{path('sites_search')}}" method="POST">
				<div class="col-12 col-lg-auto">
					<label for="input-search-sites">Le nom contient :</label>
				</div>
				<div class="col-6 col-lg-auto">
					<input type="text" class="form-control" id="input-search-sites" name="filter_sites">
				</div>
				<div class="col-6 col-lg-auto">
					<button type="submit" class="btn btn-primary mb-3">Rechercher</button>
				</div>
			</form>
		</div>

		<div class="table-sites">
			<table class="table">
				<thead>
					<tr>
						<th>Ville</th>
						{% if is_granted("ROLE_ADMIN") %}
							<th>Actions</th>
						{% endif %}
					</tr>
				</thead>
				<tbody>
					{% for site in lstSites %}
						<tr>
							<td>
								<a href="{{path('sorties_site',{id:site.id})}}">{{site.getNomSite}}</a>
							</td>
							{% if is_granted("ROLE_ADMIN") %}
								<td>
									<a href="{{path('site_update',{id:site.id})}}" class="btn btn-warning btn-border-radius">
										<i class="fas fa-edit"></i>
									</a>

									<button type="button" class="mt-2 mt-lg-0 btn btn-danger btn-border-radius" data-elementid="{{site.id}}" data-elementnom="{{site.nomSite}}" onclick="deleteElement(this)" data-bs-toggle="modal" data-bs-target="#exampleModal">
										<i class="fas fa-trash"></i>
									</button>
								</td>
							{% endif %}
						</tr>
					{% endfor %}
					{% if is_granted("ROLE_ADMIN") %}
						<tr>
							<form action="{{path('site_add')}}" method="post">
								<td><input type="text" class="form-control" name="search_sites" placeholder="Nom du site" required></td>
								<td>
									<button class="mt-3 mt-lg-0 btn btn-success" type="submit">Ajouter</button>
								</td>
							</form>
						</tr>
					{% endif %}
				</tbody>
			</table>
		</div>
	</div>

{% endblock %}

templates/sites/sitesmodif.html.twig
{% extends 'base.html.twig' %}

{% block body %}

	<div class="h" id="gestion-sites">

		{{ form_start(forms) }}
		{{ form_widget(forms) }}
		<div class="my-5 d-grid gap-2 col-6 mx-auto">
			<button class="py-3 btn btn-primary fw-bolder" type="submit">Modifier</button>
			<a class="py-3 btn btn-danger fw-bolder" href="{{ path('sites') }}">Retour</a>
		</div>
		{{ form_end(forms) }}
	</div>


{% endblock %}

templates/sites/sorties.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="h1">
		Sorties du site {{site}}
	</div>
    <table class="table">
        <thead>
            <tr>
                <td scope="col">Organisateur</td>
                <td scope="col">Nom sortie</td>
                <td scope="col">Nombre inscriptions max</td>
                <td scope="col">Lieu</td>
                <td scope="col">État</td>
            </tr>
        </thead>
        <tbody>
            {% for sortie in sorties %}
                <tr>
                    <td scope="row">{{sortie.organisateur.nom}} {{sortie.organisateur.prenom}}</td>
                    <td scope="row">{{sortie.nom}}</td>
                    <td scope="row">{{sortie.nbInscriptionsMax}}</td>
                    <td scope="row">{{sortie.lieux.getNomLieu()}} ({{sortie.lieux.getRue()}})</td>
                    <td scope="row">{{sortie.etats.getLibelle()}}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}