src/Entity/Villes.php
<?php

namespace App\Entity;

use App\Repository\VillesRepository;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=VillesRepository::class)
 */
class Villes
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=30)
     * @Assert\NotBlank
     * @Assert\Length(min=3)
     */
    private $nom_ville;

    /**
     * @ORM\Column(type="string", length=10)
     * @Assert\NotBlank
     * @Assert\Length(min=3)
     */
    private $code_postal;

    /**
     * @ORM\OneToMany(targetEntity=Lieux::class, mappedBy="villes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $lieux;

    public function __construct()
    {
        $this->lieux = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomVille(): ?string
    {
        return $this->nom_ville;
    }

    public function setNomVille(string $nom_ville): self
    {
        $this->nom_ville = $nom_ville;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    /**
     * @return Collection|Lieux[]
     */
    public function getLieux(): Collection
    {
        return $this->lieux;
    }

    public function addLieux(Lieux $lieux): self
    {
        if (!$this->lieux->contains($lieux)) {
            $this->lieux[] = $lieux;
            $lieux->setVilles($this);
        }

        return $this;
    }

    public function removeLieux(Lieux $lieux): self
    {
        if ($this->lieux->removeElement($lieux)) {
            // set the owning side to null (unless already changed)
            if ($lieux->getVilles() === $this) {
                $lieux->setVilles(null);
            }
        }

        return $this;
    }

    public function json()
    {
        $json = json_encode("{'lieux':" . $this->getLieux() . "}");
    }
}

src/Form/VilleType.php
<?php

namespace App\Form;

use App\Entity\Villes;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VilleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom_ville', null, ["label" => "Nom ville*:"])
            ->add('code_postal', null, ["label" => "Code postal*:"]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Villes::class,
        ]);
    }
}

src/Controller/VilleController.php
<?php

namespace App\Controller;

use App\Entity\Villes;
use App\Form\VilleType;
use App\Repository\LieuxRepository;
use App\Repository\SortiesRepository;
use App\Repository\VillesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class VilleController extends AbstractController
{

    /**
     * @Route("/ville", name="app_ville")
     */
    public function index(VillesRepository $villesRepository, Request $request, EntityManagerInterface $em): Response
    {

        $ville = new Villes;
        $formVille = $this->createForm(VilleType::class, $ville);
        $formVille->handleRequest($request);

        if ($formVille->isSubmitted() && $formVille->isValid()) {

            //vérification de l'existance de la ville 
            $listeVilles = $villesRepository->findAll();

            foreach ($listeVilles as $villeInDB) {

                //dans le cas ou la ville existe déja j'annule l'enregistrement 
                if ($villeInDB->getNomVille() == $ville->getNomVille() or $villeInDB->getCodePostal() == $ville->getCodePostal()) {
                    $this->addFlash('error', ' la ville existe déja');
                    return  $this->redirectToRoute('app_ville');
                }
            }

            // dans l'autre cas j'enregistre la ville dans la db
            $em->persist($ville);
            $em->flush();

            // je signale l'utilisateur 
            $this->addFlash('success', ' de la ville ok');
            return  $this->redirectToRoute('app_ville');
        }

        return $this->render('ville/index.html.twig', [
            'villes' => $villesRepository->findAll(),
            'formVille' => $formVille->createView()
        ]);
    }

    /**
     * @Route("/ville/find", name="app_ville_find")
     */
    public function villeFind(Request $request, VillesRepository $villesRepository): Response
    {
        //récuperation de la requête  de l'utilisateur 
        if ($request->request->get('myWord')) {

            return $this->render('ville/index.html.twig', [
                //j'appelle mon DQL ici pour la recherche par mot clé 
                'villes' => $villesRepository->findByFieldName($request->request->get('myWord')),
            ]);
        }
        return $this->redirectToRoute('app_ville');
    }

    /**
     * @Route("/admin/ville/{id}/eddit", name="app_ville_eddit")
     */
    public function villeEddit(Villes $ville, Request $request, EntityManagerInterface $em): Response
    {

        $formVille = $this->createForm(VilleType::class, $ville);
        $formVille->handleRequest($request);

        if ($formVille->isSubmitted() && $formVille->isValid()) {
            $em->persist($ville);
            $em->flush();
            return $this->redirectToRoute('app_ville');
        };

        return $this->render('ville/eddit.html.twig', [
            'formVille' => $formVille->createView(),
            'ville' => $ville
        ]);
    }


    /**
     * @Route("/admin/ville/{id}/delete", name="app_ville_delete")
     */
    public function villeDelete(Villes $ville, EntityManagerInterface $em, LieuxRepository $lieuxRepository, SortiesRepository $sortiesRepository): Response
    {
        //rechercher les lieux dans la ville  
        $allLieux = $lieuxRepository->findBy(['villes' => $ville->getId()]);

        //supprimer les lieux dans la ville  
        foreach ($allLieux as $lieu) {
            $allSorties = $sortiesRepository->findBy(['lieux' => $lieu->getId()]);

            //en cas de changement de lieu je ne supprime pas la sortie
            // je mets la valeur du lieu à null 
            foreach ($allSorties as $sortie) {
                $sortie->setLieux(NULL);
            }
            $em->remove($lieu);
        }

        $em->remove($ville);
        $em->flush();

        // je signale l'utilisateur 
        $this->addFlash('success', 'suppression de la ville ok');

        return $this->redirectToRoute('app_ville');
    }
}

templates/ville/eddit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier une Villle
{% endblock %}

{% block body %}


	<h2 class="my-5 text-uppercase text-center">Modification de la ville
		{{ville.nomVille}}</h2>
	<div class="row container ">
		<div class="col-lg-6 mx-auto">

			{{ form_start(formVille) }}
			{{ form_widget(formVille) }}

			<div class="my-5 d-grid gap-2 col-6 mx-auto">
				<button class="py-3 btn btn-primary fw-bolder" type="submit">Modifier</button>
				<a class="py-3 btn btn-danger fw-bolder" href="{{ path('app_ville') }}">Retour</a>
			</div>
			{{ form_end(formVille) }}
		</div>
	</div>

{% endblock %}

templates/ville/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestionnaire de villes!
{% endblock %}

{% block body %}


	<div>
		<h1 class="mt-5 mb-3 text-uppercase">Gestion des villes</h1>

		<div>
			{%  for type , messages  in app.flashes(['success','error','info']) %}
				{% for message in messages %}
					<div class="alert alert-{{ (type =='error') ? 'danger' : type }} text-center" role="alert">
						{{ message }}
					</div>
				{% endfor %}
			{% endfor %}
		</div>

		<div>
			<div class="col-12">
				<p class="fw-bolder">
					Filter les villes</p>
			</div>
			<form action="{{ path('app_ville_find') }}" class="my-4 row" method="POST">
				<div class="col-12 col-lg-2">
					Le nom contient :</div>
				<div class="col-6 col-lg-4">
					<input class="form-control rounded-pill" type="text" name="myWord"></div>
				<div class="col-6 col-lg-2">
					<button class="btn btn-success" type="submit">
						Rechercher</button>
				</div>
			</form>

		</div>

		<div class="row">
			<div class="col-lg-8">
				<div class="table-responsive table-wrapper-scroll-y my-custom-scrollbar ">
					<table class="table">
						<thead class="table-dark sticky-top">
							<tr>
								<th scope="col">Nom de la ville
								</th>
								<th scope="col">Code postal</th>

								{% if is_granted("ROLE_ADMIN") %}
									<th scope="col">Actions</th>
								{% endif %}
							</tr>
						</thead>
						<tbody>
							{% for ville in villes %}
								<tr>
									<th>{{ville.nomVille}}</th>
									<td>{{ville.codePostal}}</td>

									{% if is_granted("ROLE_ADMIN") %}
										<td>
											<a class="btn btn-warning text-white btn-border-radius" href="{{ path('app_ville_eddit', {id:ville.id}) }}">
												<i class="fas fa-edit"></i>
											</a>

											<button class="my-2 m-lg-0 btn btn-danger btn-border-radius" type="button" data-elementid="{{ville.id}}" data-elementnom="{{ville.nomVille}}" onclick="deleteElement(this)" data-bs-toggle="modal" data-bs-target="#exampleModal">
												<i class="fas fa-trash"></i>
											</button>

										</td>
									{% endif %}
								</tr>
							{% endfor %}
							<tr>
								{% if is_granted("ROLE_ADMIN")  and (formVille is defined) %}

									{{ form_start(formVille) }}
									<th>{{ form_row(formVille.nom_ville,{'attr': {'class': 'mt-4 mt-sm-0'}}) }}</th>
									<th>{{ form_row(formVille.code_postal,{'attr': {'class': 'task_field'}}) }}</th>
									<td>
										<div class="mt-4 mt-lg-0">
											<button class="my-4 btn btn-success text-white" type="submit">Ajouter</button>
										</div>
									</td>
									{{ form_end(formVille) }}

								{% endif %}
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>

	{% endblock %}