src/Entity/Lieux.php
<?php

namespace App\Entity;

use App\Repository\LieuxRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Serializer\Annotation\Groups;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LieuxRepository::class)
 */
class Lieux
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups("lieu:read")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=30)
     * @Groups("lieu:read")
     */
    private $nom_lieu;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     * @Groups("lieu:read")
     */
    private $rue;

    /**
     * @ORM\Column(type="float", nullable=true)
     * @Groups("lieu:read")
     */
    private $latitude;

    /**
     * @ORM\Column(type="float", nullable=true)
     * @Groups("lieu:read")
     */
    private $longitude;

    /**
     * @ORM\ManyToOne(targetEntity=Villes::class, inversedBy="lieux")
     * @ORM\JoinColumn(nullable=false)
     * @Groups("lieu:read")
     */
    private $villes;

    /**
     * @ORM\OneToMany(targetEntity=Sorties::class, mappedBy="lieux")
     * @ORM\JoinColumn(nullable=false)
     */
    private $sorties;

    public function __construct()
    {
        $this->sorties = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomLieu(): ?string
    {
        return $this->nom_lieu;
    }

    public function setNomLieu(string $nom_lieu): self
    {
        $this->nom_lieu = $nom_lieu;

        return $this;
    }

    public function getRue(): ?string
    {
        return $this->rue;
    }

    public function setRue(?string $rue): self
    {
        $this->rue = $rue;

        return $this;
    }

    public function getLatitude(): ?float
    {
        return $this->latitude;
    }

    public function setLatitude(?float $latitude): self
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getLongitude(): ?float
    {
        return $this->longitude;
    }

    public function setLongitude(?float $longitude): self
    {
        $this->longitude = $longitude;

        return $this;
    }

    public function getVilles(): ?Villes
    {
        return $this->villes;
    }

    public function setVilles(?Villes $villes): self
    {
        $this->villes = $villes;

        return $this;
    }

    /**
     * @return Collection|Sorties[]
     */
    public function getSorties(): Collection
    {
        return $this->sorties;
    }

    public function addSorty(Sorties $sorty): self
    {
        if (!$this->sorties->contains($sorty)) {
            $this->sorties[] = $sorty;
            $sorty->setLieux($this);
        }

        return $this;
    }

    public function removeSorty(Sorties $sorty): self
    {
        if ($this->sorties->removeElement($sorty)) {
            // set the owning side to null (unless already changed)
            if ($sorty->getLieux() === $this) {
                $sorty->setLieux(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->getNomLieu();
    }
}

templates/lieux/addLieu.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="h" id="gestion-sites">
		<h1 class="title-page">Créer un lieu</h1>
        {{form_start(form)}}
            <div class="input-group input-group-sm mb-3">
                <span class="input-group-text" id="inputGroup-sizing-sm">Ville*</span>
                <select class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-sm" name="ville" id="ville" required>
					<option selected></option>
					{% for ville in villes %}
							<option value="{{ville.getId()}}" name="{{ville.getId()}}">{{ville.getNomVille()}}</option>
					{% endfor %}
				</select>
            </div>

            <div class="input-group input-group-sm mb-3">
                <span class="input-group-text" id="inputGroup-sizing-sm">Nom*</span>
                <input type="text" name="nom_lieu" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-sm" required>
            </div>

            <div class="input-group input-group-sm mb-3">
                <span class="input-group-text" id="inputGroup-sizing-sm">Rue*</span>
                <input type="text" name="rue" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-sm" required>
            </div>

            <div class="input-group input-group-sm mb-3">
                <span class="input-group-text">Latitude/longitude</span>
                <input type="number" step=".00001" name="latitude" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-sm">
                <input type="number" step=".00001" name="longitude" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-sm">
            </div>

            <div class="input-group input-group-sm mb-3">
                <input type="submit" value="Ajouter" class="btn btn-success">
            </div>
        {{form_end(form)}}
    </div>
{% endblock %}

templates/lieux/editLieu.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="h" id="gestion-sites">
		<h1 class="title-page">Modification du lieu {{lieu.getNomLieu()}}</h1>
        {{form_start(form)}}
            <table>
                <tbody>
                    <tr>
                        <td>Nom</td>
                        <td></td>
                        <td><input type="text" name="nom_lieu" value="{{lieu.getNomLieu()}}"></td>
                    </tr>
                    <tr>
                        <td>Rue</td>
                        <td></td>
                        <td><input type="text" name="rue" value="{{lieu.getRue()}}"></td>
                    </tr>
                    <tr>
                        <td>Latitude</td>
                        <td></td>
                        <td><input type="number" step=".00001" name="latitude" value="{{lieu.getLatitude()}}"></td>
                    </tr>
                    <tr>
                        <td>Longitude</td>
                        <td></td>
                        <td><input type="number" step=".00001" name="longitude" value="{{lieu.getLongitude()}}"></td>
                    </tr>
                    <tr>
                        <td>Ville</td>
                        <td></td>
                        <td>
                            <select id="ville">
                                {% for ville in villes %}
                                    <option value="{{ville.getId()}}" {% if (ville.getId() == lieu.getVilles().getId()) %}{{"selected"}}{% endif %}>{{ville.getNomVille()}}</option>
                                {% endfor %}
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td><button type="submit" class="btn btn-success">Enregistrer</button><a href="{{path('showLieux')}}" class="btn btn-warning">Annuler</a></td>
                        <td></td>
                    </tr>
                </tbody>
            </table>
        {{form_end(form)}}
    </div>
{% endblock %}

templates/lieux/showLieu.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<div class="h" id="gestion-sites">
		<h1 class="title-page">Lieu "{{lieu.getNomLieu()}}"</h1>
		<table>
			<tbody>
                <tr>
					<td>Ville</td>
					<td>-> {{lieu.getVilles().getNomVille()}}</td>
				</tr>
				<tr>
					<td>Rue</td>
					<td>-> {{lieu.getRue()}}</td>
				</tr>
                {% if lieu.getLatitude() is not null %}
				<tr>
					<td>Latitude</td>
					<td>-> {{lieu.getLatitude()}}</td>
				</tr>
                {% endif %}
                {% if lieu.getLongitude() is not null %}
				<tr>
					<td>Longitude</td>
					<td>-> {{lieu.getLongitude()}}</td>
				</tr>
                {% endif %}
				{% if lieu.getLatitude() is not null and lieu.getLongitude() is not null %}
					<tr>
						<iframe width="400" height="300" style="border:0;margin-left:3%;border-radius:20px" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?width=100%25&amp;height=600&amp;hl=fr&amp;q={{lieu.getLatitude()}},{{lieu.getLongitude()}}&amp;t=&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"></iframe>
					</tr>
				{% endif %}
			</tbody>
		</table>
	</div>
{% endblock %}

templates/lieux/showLieux.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<div class="h" id="gestion-sites">
		<h1 class="title-page">Gérer les lieux</h1>

		<div class="filter">
			<h2 class="mb-3">Filter les lieux</h2>

			<form class="row g-3" action="{{path('lieux_search')}}" method="POST">
				<div class="col-12 col-lg-auto">
					<label for="input-search-lieux">Le nom contient</label>
				</div>
				<div class="col-6 col-lg-auto">
					<input type="text" class="form-control" id="input-search-lieux" name="filter_lieux">
				</div>
				<div class="col-6 col-lg-auto">
					<button type="submit" class="btn btn-primary mb-3">Rechercher</button>
				</div>
			</form>
		</div>

		<div class="table-sites">
			<table class="table">
				<thead>
					<tr>
						<th>Nom</th>
						<th>Rue</th>
						{% if is_granted("ROLE_ADMIN") %}
							<th>Actions</th>
						{% endif %}
					</tr>
				</thead>
				<tbody>
					{% for lieu in lieux %}
						<tr>
							<td>
								<a href="{{path('showLieu',{l:lieu.id})}}">{{lieu.getNomLieu()}}</a>
							</td>
							<td>{{lieu.getRue()}}</td>
							{% if is_granted("ROLE_ADMIN") %}
								<td>
									<a href="{{path('editLieu',{l:lieu.getId()})}}" class="my-2 my-lg-0 btn btn-warning btn-border-radius">
										<i class="fas fa-edit"></i>
									</a>

									<button type="button" class="mt-2 mt-lg-0 btn btn-danger btn-border-radius" data-elementid="{{lieu.id}}" data-elementnom="{{lieu.nomLieu}}" onclick="deleteElement(this)" data-bs-toggle="modal" data-bs-target="#exampleModal">
										<i class="fas fa-trash"></i>
									</button>

								</td>
							{% endif %}
						</tr>
					{% endfor %}
				</tbody>
			</tbody>
		</table>
	</div>
	{% if is_granted("ROLE_ADMIN") %}
		<a href="{{'addLieu'}}" class="my-2 btn btn-success">Ajouter un lieu</a>
	{% endif %}
</div>{% endblock %}